### ISSUE TITLE
Pattern for getting graphviz to draw timeline charts?

### ISSUE THREAD

**Issue by modulovalue** [stereobooster/exact-online-string-matching#1]
Hello @stereobooster,

I wanted to ask if you could briefly share how one can get graphviz to produce the timeline graphs that you are generating here and on your parsing page.

My first guess was that the year labels are nodes that are connected by invisible edges and all nodes of a year are contained in a single cluster?

And thank you for collecting and sharing all of that, very very cool!

**Comment by stereobooster** [comment]
The key technique for timeline is `rank = same`, after that it's matter of taste on how you want to style it

```dot
digraph d {
  node [ shape=plaintext,fontsize=25 ];
  1957 -> 1958 -> 1959 

  node [ fontsize=30, style=filled ];
  { rank = same ; 1957 ; "A" ; "B"  }
  { rank = same ; 1958 ; "C" ; "D"  }
  { rank = same ; 1959 ; "E" ; "F" }

  A -> C -> E
}
```

https://astro-digital-garden.stereobooster.com/recipes/timeline-diagram/

**Comment by modulovalue** [comment]
Thank you @stereobooster!
